//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPortal.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tech
    {
        public int TechID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string JobTitle { get; set; }
        public string Location { get; set; }
        public string TechRole { get; set; }
        public string ShiftStatus { get; set; }
        public bool IsActive { get; set; }
    }
}
