//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPortal.Data.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechRole
    {
        public int TechRoleID { get; set; }
        public string TRName { get; set; }
        public bool IsActive { get; set; }
    }
}
