//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechPortal.Data.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TPDBEntities : DbContext
    {
        public TPDBEntities()
            : base("name=TPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobTitle> JobTitle { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<ShiftStatus> ShiftStatus { get; set; }
        public virtual DbSet<Tech> Tech { get; set; }
        public virtual DbSet<TechRole> TechRole { get; set; }
    }
}
